# Site Identity
title: Staat Mensch Geld
author: sn
description: Eine Analyse der systemischen Transformation und der Erosion des Bürgerlichen.

# Defaults
defaults:
  - scope:
      path: "" 
    values:
      layout: "default"

# UI Labels (Configurable without touching HTML)
ui:
  theme_button: "Switch Mode"
  default_section_label: "Links"
  menu_header: "Gitslate"
  prev_label: "Previous"
  next_label: "Next"

# Jekyll Settings
remote_theme: jekyll/minima
data_source: .
